// <auto-generated />
using System;
using Asal.OrderManagementSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asal.OrderManagementSystem.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928195739_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmad@example.com",
                            Name = "Ahmad Ali",
                            Phone = "0599123456"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@example.com",
                            Name = "Omar Khalil",
                            Phone = "0598765432"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@example.com",
                            Name = "Sara Hassan",
                            Phone = "0599555444"
                        });
                });

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItem_Price_MustBePositive", "[UnitPrice]>0");

                            t.HasCheckConstraint("CK_OrderItem_Quantity_MustBePositive", "[Quantity]>0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            OrderId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Quantity = 1,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            OrderId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Quantity = 2,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            OrderId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ProductId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 1,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            OrderId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 3,
                            UnitPrice = 14.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            OrderId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ProductId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Quantity = 2,
                            UnitPrice = 899.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            OrderId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ProductId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Quantity = 1,
                            UnitPrice = 249.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            OrderId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            ProductId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Quantity = 2,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            OrderId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ProductId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 2,
                            UnitPrice = 79.99m
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            OrderId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ProductId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Quantity = 5,
                            UnitPrice = 14.99m
                        });
                });

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_Positive", "[Price] > 0");

                            t.HasCheckConstraint("CK_Products_StockQuantity_NotNegatives", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Laptop",
                            Price = 899.99m,
                            SKU = "LAP-001",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            SKU = "MOU-001",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 79.99m,
                            SKU = "KEY-001",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "USB-C Cable",
                            Price = 14.99m,
                            SKU = "USB-001",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Monitor",
                            Price = 249.99m,
                            SKU = "MON-001",
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.Order", b =>
                {
                    b.HasOne("Asal.OrderManagementSystem.Api.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.OrderItem", b =>
                {
                    b.HasOne("Asal.OrderManagementSystem.Api.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asal.OrderManagementSystem.Api.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asal.OrderManagementSystem.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
